### ISSUE TITLE
Leaderboard UI for Switching between Points / MMR

### ISSUE THREAD

**Issue by robertvanhoesel** [stormgateworld/web#17]
Can be a simple HTML buttonset with an active/selected state saying [RP | MMR] like below.

Preferably extending https://github.com/stormgateworld/web/blob/main/src/lib/theme.ts 

![CleanShot 2024-02-05 at 19 37 36@2x](https://github.com/stormgateworld/web/assets/6642554/4c177b2b-fb69-4738-b983-4a2161f1d6eb)

![CleanShot 2024-02-05 at 19 36 00@2x](https://github.com/stormgateworld/web/assets/6642554/a5d64bf7-62f8-487f-86fb-ce3af7ec71d6)

The API already supports this sorting.

**Comment by qlemaire22** [comment]
Will have a look!

**Comment by qlemaire22** [comment]
Can be closed.
