### ISSUE TITLE
Astro file format in VSCode

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#30]
I didn't manage to make VSCode to be able to format Astro files for enabling auto-format on save for myself. 
I get this error `Failed to resolve a parser, skipping file.`.
I looked at the setup and it looks good as described here https://github.com/withastro/prettier-plugin-astro

Is there anything I am missing? Is it working on your side?

**Comment by robertvanhoesel** [comment]
Are you using the suggested Astro Language plugin for Vs Code? I think it's required to help prettier understand what part is html and ts.

**Comment by qlemaire22** [comment]
Yes, I am using this one https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode

**Comment by qlemaire22** [comment]
Yeah, I tried it without success. I might have done something wrong but I guess it is not so important

**Comment by robertvanhoesel** [comment]
I actually ran into this now too a few times, the last commit on main helped for me https://github.com/stormgateworld/web/commit/c69d561e892c2b755b74f166ec3a66df5a8e1c60
