### ISSUE TITLE
Suggestion for players without data

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#32]
I wrote it in #stormgateworld-api but writing it here as well so that it doesn't get lost.

Should we put "<1000" if we don't have a value for the rank in the leaderboard? 
Also, maybe a message when we receive a null value for RP? (not sure what to put here to be concise, maybe just "-") 
Could avoid some confusion and questions like https://discordapp.com/channels/1101590942076653660/1202683757707010128/1204773311012409384 

What do you think?

**Comment by robertvanhoesel** [comment]
Yeah I think this is wise to do. It's a bit of a temporary solution but we get enough questions about it. 

You could make the ` # - ` and ` >1000` clickable to point to the /faq page (probably we need to reformat that a bit so the the questions become markdown titles we can deeplink to)
