### ISSUE TITLE
Tool tags cut

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#40]
I tried on a smaller screen and we can see that the tags are cut at the end

<img width="1097" alt="Screenshot 2024-02-07 at 21 28 00" src="https://github.com/stormgateworld/web/assets/23478363/09de109a-ccd9-4f9f-a8cd-24d8645eefc6">

We should probably make them slightly smaller and wrap if needed

**Comment by robertvanhoesel** [comment]
- Add external link icon and domain, so we don't need a tag for it
- Decreased size of tags

![CleanShot 2024-02-09 at 19 53 37@2x](https://github.com/stormgateworld/web/assets/6642554/a7ed874b-d93e-44db-b4bf-d9b866db5b3c)
