### ISSUE TITLE
Add FAQ link

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#43]
If I am not mistaking, the FAQ is only accessible when you know the URL. 
At least I haven't found a link easily.

**Comment by qlemaire22** [comment]
@robertvanhoesel where do you think should be a good place for that? In the header?

**Comment by robertvanhoesel** [comment]
Footer before Privacy policy and such, maybe in the same swoop rewrite it to be a config array of links rather than pure html it currently is
