### ISSUE TITLE
Generated OG Image

### ISSUE THREAD

**Issue by robertvanhoesel** [stormgateworld/web#51]
Dynamically generated image previews for profiles and matches. Probably requiers some endpoint like `/players/2342345/og-image` that is always set on a page but lazily renders out the image on first request.

![CleanShot 2024-02-09 at 17 30 20@2x](https://github.com/stormgateworld/web/assets/6642554/f2896a74-0778-4458-8d39-8525c8d39fe5)

![CleanShot 2024-02-09 at 17 32 35@2x](https://github.com/stormgateworld/web/assets/6642554/587d46a7-b4df-4483-8426-2a139e311fe3)

**Comment by desmondsmall** [comment]
I can take a look at this one 🖼️
