### ISSUE TITLE
Header with blurrier background?

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#70]
<img width="883" alt="Screenshot 2024-02-13 at 09 12 32" src="https://github.com/stormgateworld/web/assets/23478363/50565200-399c-4b0c-b5ab-5c74ec5a6fd0">

I think that the header should have a blurrier background because right now it looks like both the header and the background content are simply on top of each other

**Comment by qlemaire22** [comment]
Update: it seems that it works differently on Chrome/Firefox
On Chrome, I can see the blurriness effect but not on Firefox

**Comment by robertvanhoesel** [comment]
Yep, I noticed it too on mobile Firefox. Will rethink the behavior a bit.
