### ISSUE TITLE
Remove EGC qualifier logo

### ISSUE THREAD

**Issue by qlemaire22** [stormgateworld/web#74]
I guess we should remove it now as the selected players have been announcement. Especially since the order have changed from the ones that have been announcement (Elazer is now 4th instead of TOP).

**Comment by robertvanhoesel** [comment]
Or we work with a const array of qualified players?

**Comment by qlemaire22** [comment]
Would work as well! I don't know what is best. If we do that we could include the players that got qualified through the open qualifier as well.
But I am not sure it is worth it since it ends this weekend?
