### ISSUE TITLE
Faction names inconsistency on player profile

### ISSUE THREAD

**Issue by SenorRagequit** [stormgateworld/web#78]
Currently, the factions on the player profile are somewhat inconsidstent.

Vanguard ⇾ Singular
Infernals ⇾ Plural

![grafik](https://github.com/stormgateworld/web/assets/50502395/96483652-5175-48d1-808f-7342f06e7291)

I'm not a native English speaker, so it might be correct for some linguistics reason

**Comment by forbesd7** [comment]
<img width="284" alt="Screenshot 2024-02-15 at 8 54 50" src="https://github.com/stormgateworld/web/assets/54018183/5e5ac90f-75ad-47e1-892d-00fc8257365f">

I think this is correct considering this is how they have it in the beta!

**Comment by SenorRagequit** [comment]
Ya true. Never noticed that.
