### ISSUE TITLE
Game length missing labels for graphs

### ISSUE THREAD

**Issue by SenorRagequit** [stormgateworld/web#81]
As you can see here, some labels below the graphs are missing (bottom one):

![grafik](https://github.com/stormgateworld/web/assets/50502395/adc664ee-db3f-49cb-92e8-1cc54929893e)

**Comment by robertvanhoesel** [comment]
Intended behavior of the library when there are more labels that comfortably fit.

**Comment by robertvanhoesel** [comment]
Label is shown on hover.
