### ISSUE TITLE
Change stats page layout for widescreen

### ISSUE THREAD

**Issue by SenorRagequit** [stormgateworld/web#82]
Might be personal taste, but the stats layout just screams for mobile phone.
There is so much dead space to the left and right, both activity graphs could be next to another.

![grafik](https://github.com/stormgateworld/web/assets/50502395/0975db10-0da4-47a8-a8dc-526eaf64a159)

**Comment by robertvanhoesel** [comment]
Closing for now, issue will resolve itself once more graphs are added.
